
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TakePhotoFrameWork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TakePhotoFrameWork
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'GoogleMLKit/FaceDetection'
  pod 'Firebase/Analytics', '7.11.0'
  pod 'Firebase/Crashlytics', '7.11.0'
  pod 'Firebase/Messaging', '7.11.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete('CODE_SIGNING_ALLOWED')
      config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
  end
end