
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

target 'SDKDemo' do
  
  # use online: pod 'TakePhotoFrameWork'
  # use local
  pod 'TakePhotoFrameWork', :path => 'SDK/TakePhotoFrameWork.podspec'
end
