
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

target 'SDKDemo' do
  
  pod 'TakePhotoFrameWork', :path => 'SDK/TakePhotoFrameWork.podspec'
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['ENABLE_BITCODE'] = 'NO'
#    end
#  end
#end

#install! 'cocoapods', :deterministic_uuids => false
